### ISSUE TITLE
Tracking Issue: Bors V2: Running `bors try` With Specific Parent

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#1104]
From [this issue on rust-lang/bors](https://github.com/rust-lang/bors/issues/23), it is proposed to allow try builds to be created with a specific parent commit via a `parent` parameter.

This issue is created s a tracking issue for the implementation of this feature for Bors V2.

- [x] modify parsing to support parameters https://github.com/TeamHarTex/HarTex/pull/1105
- [x] adapt the try command implementation to take a parent commit https://github.com/TeamHarTex/HarTex/pull/1106
- [x] modify the try command such that it creates try builds with a parent commit if specified https://github.com/TeamHarTex/HarTex/pull/1106

ETA: **0.2.0**

**Comment by HTG-YT** [comment]
Reference: https://github.com/rust-lang/bors/issues/23
