### ISSUE TITLE
Tracking Issue: Reorganize Interaction Commands

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#1228]
This is a tracking issue for implementing reorganization for interaction commands, specifically grouping information-related (except `about`) commands into a single `info` command with corresponding subcommands.

## Tasks

- [x] write new command specification for `info`
  - [x] unlocalized specification https://github.com/TeamHarTex/HarTex/pull/1229
  - [x] add necessary localizations
    - [x] `zh_CN` localizations https://github.com/TeamHarTex/HarTex/pull/1237
    - [x] `zh_TW` localizations https://github.com/TeamHarTex/HarTex/pull/1232
- [x] migrate `serverinfo` command as `info server`
  - [x] unlocalized subcommand specification https://github.com/TeamHarTex/HarTex/pull/1233
  - [x] add necessary localizations
    - [x] `zh_CN` localizations (existing localizations)
    - [x] `zh_TW` localizations (existing localizations)
  - [x] update command handler to reflect the change https://github.com/TeamHarTex/HarTex/pull/1234
- [x] migrate `latency` and `uptime` commands as `info bot`
  - [x] unlocalized subcommand specification https://github.com/TeamHarTex/HarTex/pull/1235
  - [x] add necessary localizations
    - [x] `zh_CN` localizations https://github.com/TeamHarTex/HarTex/pull/1237
    - [x] `zh_TW` localizations https://github.com/TeamHarTex/HarTex/pull/1236
  - [x] update command handler to reflect the change https://github.com/TeamHarTex/HarTex/pull/1238
- [x] cleanup
  - [x] remove old command specifications
    - [x] `latency` https://github.com/TeamHarTex/HarTex/pull/1238
    - [x] `uptime` https://github.com/TeamHarTex/HarTex/pull/1238
    - [x] `serverinfo`  https://github.com/TeamHarTex/HarTex/pull/1235
 
*This task list is not complete, and is subject to change.*
