### ISSUE TITLE
Tracking Issue: Improved Diagnostics

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#2106]
This tracking issue tracks the implementation of an improved display of error diagnostics for both terminal-side and client-side.

### Items
- [x] Error and panic handling (unwinding) #2105 
- [x] Send diagnostics to designated channel in support server with a generated error code
  - [x] Generate error code #2110 
  - [x] Send diagnostics #2111
- [x] Notify user of the error with the same generated error code #2111
