### ISSUE TITLE
Tracking Issue for Pull Request #2

### ISSUE THREAD

**Issue by HTGAzureX1212** [TeamHarTex/HarTex#3]
This is the tracking issue for Pull Request: 
* HarTexTeam/HarTex-rust-discord-bot#2

- [x] Command `struct` Declaration
- [x] Derive `Command` and implement the underlying methods
- - [x] Fully implement the `levelling_system_rank_command` function
- [x] Add the command to the command parser
